name: Compile Arago spot report

on:
  push:
    branches:
      - arago-florian
    paths:
      - 1-arago/report
  workflow_dispatch:

jobs:
  arago-report:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v4
      - name: Compile LaTeX report
        uses: xu-cheng/latex-action@v3
        with:
          root_file: 1-arago/report/main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: 1-arago-report
          path: 1-arago/report/main.pdf
