name: Compile Cloud chamber report

on:
  push:
    branches:
      - main
      - florian
    paths:
      - 2-cloud-chamber/report/**
  workflow_dispatch:

jobs:
  arago-report:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v4
      - name: Compile LaTeX report
        uses: xu-cheng/latex-action@v3
        with:
          root_file: 2-cloud-chamber/report/main.tex
          work_in_root_file_dir: true
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: 2-cloud-chamber-report
          path: 2-cloud-chamber/report/main.pdf
